---
output: github_document
---

This notebook generates plots from the `.csv` results produced by the corresponding python scripts.  We compare policies across constant effort (MSY-like policies), constant escapement, and the RL agent (PPO).


```{r setup}
library(tidyverse)

best_reward <- function(df) {
  df |> 
  group_by(action, rep) |>
  filter(t == max(t)) |> 
  group_by(action) |>
  summarise(mean_reward = mean(reward), sd = sd(reward)) |> 
  filter(mean_reward == max(mean_reward))
}
```


# Constant Mortality

```{r}
msy <- read_csv("../data/msy.csv.gz")
best <- best_reward(msy)
colnames(msy) <- c('t', 'rep', 'action', 'reward', 'X', 'Y', 'Z')
msy
best
```

```{r}
rewards <- msy |>
  group_by(action, rep) |>
  filter(t == max(t)) |> 
  group_by(action) |>
  summarise(mean_reward = mean(reward),
            sd = sd(reward)) 

rewards |>
  filter(action < 0.1) |>
  ggplot(aes(action, mean_reward, 
             ymin = mean_reward - 2*sd,
             ymax=mean_reward+2*sd)) +
  geom_point() + geom_ribbon(alpha=0.4)
```


```{r}
colnames(msy)
msy_sim <- msy |>
    filter(action == best$action) |> 
    group_by(rep) |>
    pivot_longer(c("X", "Y", "Z"),
                names_to = "species", values_to = "abundance") |>
    mutate(abundance = abundance + 1) # natural units

msy_sim

msy_sim |>
    filter(rep < 5) |> # filter(rep > 8) |>
    # group_by(rep) |>
    ggplot(aes(t, abundance,  col=species, group =interaction(rep,species)))+ 
        geom_line() + facet_wrap(~rep)

msy_sim |> 
  filter(rep < 4, species == "X") |>
  ggplot(aes(t, abundance, group = interaction(rep,species),  col=species)) + 
    geom_line(alpha=0.5) 


```


```{r}
msy_sim |> 
  group_by(rep) |>
  filter(t==max(t), species=="X") |>
  ggplot(aes(rep, reward)) + geom_col()
```
# TAC

80% of  MSY

```{r}
actions <- unique(msy$action)
i <- which.min(abs(actions - best$action* 0.8))
tac_sim <- msy |> 
  filter(action == actions[[i]]) |>
  pivot_longer(c("X", "Y", "Z"),
               names_to = "species", values_to = "abundance")
tac_sim |>
  filter(rep < 20) |>
  ggplot(aes(t, abundance,  col=species)) + 
    geom_line() + facet_wrap(~rep)

```
```{r}
tac_sim |> 
  group_by(rep) |>
  filter(t==max(t), species=="X") |>
  ggplot(aes(rep, reward)) + geom_col()
```

# PPO Agent


```{r}
ppo <- read_csv("../data/ppo-200.csv")
colnames(ppo) <- c("1", "t", "X", "Y", "Z", "action", "reward", "rep")
head(ppo)
```

```{r}
overall_ppo <- 
ppo |> 
  group_by(rep) |>
  filter(t==max(t)) |> ungroup() |>
  filter(reward > 0) |>
  summarise(reward = mean(reward),
            t = mean(t),
            effort = mean(action)) |>
  mutate(policy="ppo")
overall_ppo

ppo_cumulative <- ppo |> group_by(rep) |> mutate(cumulative_reward = cumsum(reward))

ppo_cumulative |> 
  filter(t==max(t)) |> 
  ggplot(aes(rep, cumulative_reward)) + geom_col()
```

```{r}
ppo_sim <- ppo |> 
  mutate(escapement = (X+1) - action * (X+1),
         effort = action) |>
  pivot_longer(c("X", "Y", "Z"),
               names_to = "species", values_to = "abundance") |>
  mutate(abundance = abundance)

ppo_sim


ppo_sim |>
  filter(rep < 4) |>
  ggplot(aes(t, abundance, col=species)) +
  geom_line(alpha=0.6) + facet_wrap(~rep)
```


```{r}
ppo_sim |>
  filter(species == "sp1") |>
  group_by(t) |>
  summarise(abundance = mean(abundance), 
            effort = mean(effort),
            escapement = mean(escapement)) |> 
  pivot_longer(-t, names_to = "metric", values_to = "population") |>
  ggplot(aes(t, population, col=metric)) + geom_line()
```






# Constant Escapement

```{r}
escapement <- read_csv("../data/escapement.csv.gz", show_col_types = FALSE)
colnames(escapement) <- c('t', 'rep', 'action', 'reward', 'X', 'Y', 'Z')
escapement

## Determine which level of constant escapement gives highest net reward
best_e <- best_reward(escapement)
best_e
```

```{r}
esc_sims <- escapement |> 
  filter(action == best_e$action) |>
  pivot_longer(c("X", "Y", "Z"),
               names_to = "species", values_to = "abundance") |>
  mutate(abundance = abundance + 1) |>
  rename(escapement = action)

esc_sims |>
  filter(rep < 4) |>
  ggplot(aes(t, abundance, col=species)) + geom_line() +
  geom_line(aes(t, escapement), col="grey50") +
  facet_wrap(~rep)
```


```{r}
rewards <- escapement |>
  group_by(action, rep) |>
  filter(t == max(t)) |> 
  group_by(action) |>
  summarise(mean_reward = mean(reward),
            sd = sd(reward)) 

rewards |>
  ggplot(aes(action, mean_reward, 
             ymin = mean_reward - 2*sd,
             ymax=mean_reward+2*sd)) +
  geom_point() + geom_ribbon(alpha=0.4)
```


# Millie's suggestion for plots:

```{r}
msy_sim <- msy_sim |> mutate(type = "Opt const mortality", cumulative_reward = reward)
tac_sim <- tac_sim |>
    mutate(abundance = abundance + 1) |>
    mutate(type = "80% opt const mortality", cumulative_reward = reward)
ppo_sim <- ppo_sim |> mutate(type = "DRL")
ppo_sim <- within(ppo_sim, rm("1", "effort", "escapement"))
ppo_sim <- ppo_sim |>
    group_by(rep, species) |>
    mutate(cumulative_reward = cumsum(reward))
```

```{r}
ppo_sim
```

```{r}
ppo_sim <- within(ppo_sim, rm("reward"))
msy_sim <- within(msy_sim, rm("reward"))
tac_sim <- within(tac_sim, rm("reward"))
all_sim <- bind_rows(msy_sim, tac_sim, ppo_sim)
ppo_sim
msy_sim
tac_sim
all_sim
```

```{r}
all_sim |> #filter(rep < 10, species == "X") |> 
    group_by(rep) |>
    filter(t==max(t), rep < 10, species == "X") |>
    ggplot(aes(rep, cumulative_reward)) + geom_col() +
    facet_wrap(~type)

msy_sim |> 
  group_by(rep) |>
  filter(t==max(t), species=="X", rep < 10) |>
  ggplot(aes(rep, cumulative_reward)) + geom_col()

tac_sim |> 
  group_by(rep) |>
  filter(t==max(t), species=="X", rep < 10) |>
  ggplot(aes(rep, cumulative_reward)) + geom_col()

all_sim |> 
    mutate(across(type, factor, levels = c("Opt const mortality", "80% opt const mortality", 
                                           "DRL"))) |>
    group_by(rep, type) |>
    filter(t==max(t), species=="X", rep < 10) |>
    ggplot(aes(rep, cumulative_reward)) + 
        geom_col()  + 
        facet_wrap(~type) + 
        labs(y = "reward", x = "repetition")


```

```{r}
all_sim |> 
    mutate(across(type, factor, levels = c("Opt const mortality", "80% opt const mortality", 
                                           "DRL"))) |>
    group_by(rep, type) |>
    filter(rep == 0) |>
    ggplot(aes(t, abundance, col = species)) + 
        geom_line()  + 
        facet_wrap(~type) + 
        labs(y = "reward", x = "repetition")
all_sim |>
    group_by(rep,type) |>
    filter(rep<10) |>
    ggplot(aes(t, action)) + 
    geom_line()  + 
    facet_wrap(~type) + 
    labs(y = "action", x = "repetition")
    




#all_sim |> group_by(rep) |> filter(t==max(t), species == "X") |> group_by(t)
```



```{r}
all_sim |> 
    mutate(across(type, factor, levels = c("Opt const mortality", "80% opt const mortality", 
                                           "DRL"))) |>
    group_by(rep, type) |>
    filter(t==max(t), species=="X", rep < 10) |>
    ggplot(aes(rep,t)) + 
        geom_col()  + 
        facet_wrap(~type) + 
        labs(y = "episode length", x = "repetition") +
        theme(axis.text.x = element_blank())
```









